### ISSUE TITLE
typo in healthcheck maven dependency

### ISSUE THREAD

**Issue by petenorth** [redhat-developer/reactive-microservices-in-java#1]
Hi,

I think that there is a typo in the following pom.xml file

openshift/hello-microservice-openshift-health-checks/pom.xml

The healthcheck maven dependency should be 

    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-health-check</artifactId>
    </dependency>

i.e. vertx-health-check rather than vertx-health-checks

**Comment by cescoffier** [comment]
Absolutely !
