### ISSUE TITLE
HelloConsumerWithCircuitBreakerHttpVerticle. Circuit Breaker don't rediscover endpoint after reset

### ISSUE THREAD

**Issue by gvisoc** [redhat-developer/reactive-microservices-in-java#7]
When following the book walkthrough, when scaling to 0 pods the hello-microservice to open the circuit and later rescale to 1 pod to see the circuit closed again, it won't close as the Service Discovery code won't execute, so it wouldn't find the new pod. Some code has to be attached to the halfOpenHandler to re-discover the service.

**Comment by cescoffier** [comment]
You are right. 

This line is missing:

```
circuit.halfOpenHandler(v -> single.subscribe(client -> this.hello = client));
```
