### ISSUE TITLE
No handlers for address hello

### ISSUE THREAD

**Issue by ghost** [redhat-developer/reactive-microservices-in-java#8]
I am trying the message-based example, but after doing everything I get that error when I visit localhost::8082. 
Also, I do not see any resources/ folder in the generated project.
By the way, this is created via start.vertx.io page and with Gradle,  rather than via Maven, as mentioned in the book. Is it something to do with the configuration of Inifinispan?

**Comment by manideepl** [comment]
Trying to remove the issue
